PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZORDER_TC_04'
  MODULE ZORDER_TC_04_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZORDER_TC_04_CHANGE_COL_ATTR.
  LOOP AT   LT_DATA2
       INTO LWA_DATA2
       WITH CONTROL ZORDER_TC_04
       CURSOR ZORDER_TC_04-CURRENT_LINE.
    MODULE ZORDER_TC_04_GET_LINES.
*&SPWIZARD:   MODULE ZORDER_TC_04_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_0200.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZORDER_TC_04'
  LOOP AT LT_DATA2.
    CHAIN.
      FIELD LWA_DATA2-ONO.
      FIELD LWA_DATA2-OINO.
      FIELD LWA_DATA2-ODESC.
      FIELD LWA_DATA2-ICOST.
    endchain.
  ENDLOOP.
  MODULE ZORDER_TC_04_USER_COMMAND.
*&SPWIZARD: MODULE ZORDER_TC_04_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZORDER_TC_04_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0200.