PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZORDER_TC1_04'
  MODULE ZORDER_TC1_04_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZORDER_TC1_04_CHANGE_COL_ATTR.
  LOOP AT   LT_DATA1
       INTO LWA_DATA1
       WITH CONTROL ZORDER_TC1_04
       CURSOR ZORDER_TC1_04-CURRENT_LINE.
    MODULE ZORDER_TC1_04_GET_LINES.
*&SPWIZARD:   MODULE ZORDER_TC1_04_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_0300.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZORDER_TC1_04'
  LOOP AT LT_DATA1.
    CHAIN.
      FIELD LWA_DATA1-ONO.
      FIELD LWA_DATA1-OINO.
      FIELD LWA_DATA1-ODESC.
      FIELD LWA_DATA1-ICOST.
    endchain.
  ENDLOOP.
  MODULE ZORDER_TC1_04_USER_COMMAND.
*&SPWIZARD: MODULE ZORDER_TC1_04_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZORDER_TC1_04_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0300.