PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'ZORDER_TBS1_04'
  MODULE ZORDER_TBS1_04_ACTIVE_TAB_SET.
  CALL SUBSCREEN ZORDER_TBS1_04_SCA
    INCLUDING G_ZORDER_TBS1_04-PROG G_ZORDER_TBS1_04-SUBSCREEN.
* MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'ZORDER_TBS1_04'
  CALL SUBSCREEN ZORDER_TBS1_04_SCA.
  MODULE ZORDER_TBS1_04_ACTIVE_TAB_GET.
 MODULE USER_COMMAND_0100.